language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
install:
  - pear upgrade pear-1.10.1
  - pear install php_codesniffer
  - phpenv rehash
script:
  - phpcs HTTP2.php HTTP2/
  - pear run-tests -d tests/

